include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - build/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
    sort_constructors_first: true
    unnecessary_lambdas: true
    prefer_relative_imports: true
